### ISSUE TITLE
Support Grafana

### ISSUE THREAD

**Issue by making** [cloudfoundry/log-cache#102]
As a CF operator, it would be awesome if we could use log-cache as a Grafana Datasoruce that works as a drop-in replacement of Prometheus.
To monitor cf with promethes+grafana, firehose nozzle like firehose-exporter is usually required. To maintain monitoring systems aside cf is not that easy. If Grafana can talk to LogCache directly, it's quite convenient.

To support Grafana, as far as I'm aware, following functionalities seems to be missing

* Support [`/api/v1/series` API](https://prometheus.io/docs/prometheus/latest/querying/api/#finding-series-by-label-matchers)
* Operators support something like `/api/v1/query?query=1%2B1&time=1549982621.223` which is used as a validation query.
* Authorization other than UAA token

**Comment by jtuchscherer** [comment]
@making We won't be able to support Grafana in log-cache for several reasons. In order to fully support Grafana, we would need to add a few endpoints to query series and label values. These endpoints would be very hard to create. Log-cache is not optimized to store time-series data, but to store logs.

But we are in the process of publishing a metric store to the open source world that will bring full grafana support. Stay tuned for the announcement during CF summit
