### ISSUE TITLE
Log-cache process consuming 50% of the memory in the VMs

### ISSUE THREAD

**Issue by 1kaushik1** [cloudfoundry/log-cache#108]
Hi, 
Its more of a question -I can see log-cache process is  consuming around 50% of the memory in my doppler VMs. So Is this a normal behavior (50% of total memory) for log-cache since its persisting data in memory.
Is there a way to flush out all the logs ?

Thanks

**Comment by pianohacker** [comment]
Yes, this is expected behavior. Log Cache will continually monitor memory usage on the VMs, and drop logs as needed so as not to overwhelm the system. With a rough target of 50%, we haven't seen this adversely affect other components on the system.

Note that this target is a percentage, not an absolute amount, so scaling the VMs will not change this. 

If you're seeing issues on your Doppler VMs, please let us know! You can adjust the memory usage target with the `memory_limit_percent` property (https://github.com/cloudfoundry/log-cache-release/blob/develop/jobs/log-cache/spec#L35), but we don't expect most folks to have to use that.

**Comment by pianohacker** [comment]
I'm going to close this out for now; please let us know if you have any further questions!
