### ISSUE TITLE
Writes into a single node log-cache are discarded when LocalOnly isn't set

### ISSUE THREAD

**Issue by wfernandes** [cloudfoundry/log-cache#42]
We tried to write some logs into a single log-cache node. We didn't set `LocalOnly` and noticed that the logs were being discarded. This seems un-intuitive. It would be strange to expect clients to change the way they talk to log-cache based on knowledge of the cluster size.

cc/ @jasonkeene

**Comment by jasonkeene** [comment]
This was deployed without a scheduler which is likely why everything was being discarded. Since we only had a single log-cache node we thought the scheduler wouldn't be needed.

This raises the following questions:

- For small footprint environments where only a single log-cache node is being used, should we support deployments without a scheduler since the single node will always be the route for all logs?
- For ease of use by developers and in testing environments that do not require HA, do we want to support a single node experience?

**Comment by hev** [comment]
Thanks for the follow up. I think for now we are ok with the scheduler being deployed, even in Small Footprint configurations.
