### ISSUE TITLE
**Proposal** Group Reader as a CF application

### ISSUE THREAD

**Issue by poy** [cloudfoundry/log-cache#48]
**Problem Statement**
Groups provide a way for consumers to shard their data. However, groups can also be given many `source_id`s which can make capacity planning difficult.

The preferred mechanism to consume Log Cache has thus far been to cater to the self-service model where an app developer can push the consumer to their space. The group reader should fall into this category to allow for an developer to manage their own capacity needs.

**Other Requirements**
There are other consumers that are still deployed via bosh that require the group reader. They should be able to still deploy the group reader as a collocated agent.

**Things to Change**
* Breakout group reader concerns from gateway
* Breakout group reader concerns from scheduler
* Breakout group reader concerns from cf-auth-proxy
* Group reader should use HTTPS via Gorouter to talk with Log Cache

**Things to Add to support CF App**
* Group reader will support basic auth (*NOTE* a bosh deployed group reader will sill want to use gRPC with mTLS)
* Group reader scheduler will use CloudController to find group reader instances (*NOTE* a bosh deployed group reader will sill want to use bosh links)
* Group reader scheduler uses HTTPS via Gorouter to talk with group reader app instances (*NOTE* we still want to use gRPC with mTLS for bosh deployed)

**Comment by hev** [comment]
This proposal seems to outline the changes to remove the groups functionality from the bosh release which I don't agree with since it is required for operators to forward platform metrics.  I could see perhaps limiting the group API to only gRPC and mutual TLS and forcing app developers to manage groups independently with a provided app but not offering via gRPC seems limiting.
